language: java
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
mvn test -B
./mvnw test -B
install: 
  - mvn -N io.takari:maven:wrapper 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk8
